import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'km' | 'en';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  km: {
    'nav.home': 'ទំព័រដើម',
    'nav.about': 'អំពីយើង',
    'nav.courses': 'វគ្គសិក្សា',
    'nav.gallery': 'សកម្មភាព',
    'nav.contact': 'ទំនាក់ទំនង',
    'nav.login': 'ចូលគណនីសិស្ស',
    'nav.register': 'ចុះឈ្មោះឥឡូវនេះ',
    'hero.badge': 'ស្ថាប័នបណ្តុះបណ្តាល IT ឈានមុខគេ',
    'hero.title.1': 'អភិវឌ្ឍជំនាញឌីជីថលរបស់អ្នកជាមួយ',
    'hero.title.2': 'ភី អិល ស៊ី',
    'hero.desc': 'យើងផ្តល់ជូននូវកម្មវិធីសិក្សាដែលផ្តោតលើការអនុវត្តជាក់ស្តែង ជួយឱ្យអ្នកទទួលបានចំណេះដឹងពិតប្រាកដ និងត្រៀមខ្លួនរួចរាល់សម្រាប់ទីផ្សារការងារ។',
    'hero.btn.courses': 'ស្វែងរកវគ្គសិក្សា',
    'hero.btn.contact': 'ទំនាក់ទំនងយើង',
    'courses.title': 'វគ្គសិក្សាសំខាន់ៗ',
    'courses.desc': 'ស្វែងរកវគ្គសិក្សាដែលស័ក្តិសមជាមួយអ្នក។ ថ្នាក់រៀនមានបំពាក់កុំព្យូទ័រទំនើបៗ និងអនុវត្តជាក់ស្តែង ១០០%។',
    'courses.duration': 'រយៈពេលសិក្សា',
    'courses.details': 'មើលលម្អិត',
    'faq.title': 'សំណួរដែលសួរញឹកញាប់',
    'faq.q1': 'តើវគ្គសិក្សាមួយមានរយៈពេលប៉ុន្មាន?',
    'faq.a1': 'រយៈពេលសិក្សាអាស្រ័យលើវគ្គនីមួយៗ ជាទូទៅមានចាប់ពី ៣ ខែ ទៅ ៤ ខែ។',
    'faq.q2': 'តើមានការបញ្ចុះតម្លៃសម្រាប់សិស្សដែរឬទេ?',
    'faq.a2': 'យើងមានការបញ្ចុះតម្លៃពិសេសសម្រាប់សិស្ស និស្សិត និងចុះឈ្មោះជាក្រុម។',
    'faq.q3': 'តើមានផ្តល់វិញ្ញាបនបត្រពេលរៀនចប់ទេ?',
    'faq.a3': 'បាទ/ចាស យើងនឹងផ្តល់វិញ្ញាបនបត្រដែលមានការទទួលស្គាល់បន្ទាប់ពីបញ្ចប់វគ្គសិក្សាដោយជោគជ័យ។',
    'faq.q4': 'តើខ្ញុំអាចចុះឈ្មោះចូលរៀនដោយរបៀបណា?',
    'faq.a4': 'លោកអ្នកអាចចុះឈ្មោះតាមរយៈទម្រង់អនឡាញ ទូរស័ព្ទ ឬអញ្ជើញមកកាន់មជ្ឈមណ្ឌលផ្ទាល់។',
    'gallery.title': 'សកម្មភាពសិស្ស',
    'gallery.desc': 'រូបភាពសកម្មភាពសិក្សា និងការអនុវត្តជាក់ស្តែង',
    'gallery.alt': 'សកម្មភាពទី',
    'contact.title': 'ទំនាក់ទំនង និងចុះឈ្មោះ',
    'contact.desc': 'មកកាន់មជ្ឈមណ្ឌលផ្ទាល់ ឬទំនាក់ទំនងតាមរយៈព័ត៌មានខាងក្រោម',
    'contact.address': 'អាសយដ្ឋាន',
    'contact.address.text': 'ភូមិក្បាលស្ពាន២ សង្កាត់អូរជ្រៅ ក្រុងប៉ោយប៉ែត ខេត្ដបន្ទាយមានជ័យ',
    'contact.phone': 'ទូរស័ព្ទ',
    'contact.email': 'អ៊ីមែល',
    'contact.form.title': 'ទម្រង់ចុះឈ្មោះ',
    'contact.form.name': 'ឈ្មោះពេញ',
    'contact.form.name.ph': 'បញ្ចូលឈ្មោះរបស់អ្នក',
    'contact.form.tel': 'លេខទូរស័ព្ទ',
    'contact.form.tel.ph': 'បញ្ចូលលេខទូរស័ព្ទ',
    'contact.form.course': 'ជ្រើសរើសវគ្គសិក្សា',
    'contact.form.msg': 'សារបន្ថែម (បើមាន)',
    'contact.form.msg.ph': 'សរសេរសារបន្ថែម...',
    'contact.form.submit': 'បញ្ជូនការចុះឈ្មោះ',
    'contact.form.success': 'ចុះឈ្មោះបានជោគជ័យ! យើងនឹងទាក់ទងទៅអ្នកវិញឆាប់ៗ។',
    'footer.desc': 'មជ្ឈមណ្ឌលបណ្តុះបណ្តាលជំនាញកុំព្យូទ័រឈានមុខគេ ដែលផ្តល់នូវចំណេះដឹងពិតប្រាកដ និងធានាគុណភាពសិក្សា។',
    'footer.links': 'តំណភ្ជាប់រហ័ស',
    'footer.all_courses': 'វគ្គសិក្សាទាំងអស់',
    'footer.hours': 'ម៉ោងធ្វើការ & សិក្សា',
    'footer.days': 'ច័ន្ទ - សុក្រ',
    'footer.time': '៨:០០ ព្រឹក - ៨:០០ យប់',
    'footer.copyright': 'រក្សាសិទ្ធិដោយ ភី អិល ស៊ី កុំព្យូទ័រ.',
    'footer.location': 'ទីតាំង: ក្រុងប៉ោយប៉ែត',
    'footer.phone': 'លេខទូរស័ព្ទ',
    'login.student': 'ចូលគណនីសិស្ស',
    'login.admin': 'ចូលប្រព័ន្ធគ្រប់គ្រង',
    'login.student.desc': 'សូមបញ្ចូលលេខសម្គាល់សិស្ស និងពាក្យសម្ងាត់',
    'login.admin.desc': 'សូមបញ្ចូលឈ្មោះអ្នកប្រើប្រាស់ និងពាក្យសម្ងាត់',
    'login.student.btn': 'ចូលផ្ទាំងសិស្ស',
    'login.admin.btn': 'ចូលប្រព័ន្ធ',
    'login.user': 'ឈ្មោះអ្នកប្រើប្រាស់',
    'login.student_id': 'លេខសម្គាល់សិស្ស',
    'login.pass': 'ពាក្យសម្ងាត់',
    'about.title': 'អំពីយើង',
    'about.desc': 'ស្វែងយល់ពីគោលដៅ និងតម្លៃដែលយើងប្រកាន់ខ្ជាប់',
    'about.mission': 'បេសកកម្ម',
    'about.mission.desc': 'ផ្តល់ជូនការអប់រំផ្នែកកុំព្យូទ័រប្រកបដោយគុណភាពខ្ពស់ ផ្តោតលើការអនុវត្តជាក់ស្តែង ដើម្បីឆ្លើយតបនឹងតម្រូវការទីផ្សារការងារបច្ចុប្បន្ន។',
    'about.vision': 'ចក្ខុវិស័យ',
    'about.vision.desc': 'ក្លាយជាមជ្ឈមណ្ឌលបណ្តុះបណ្តាលបច្ចេកវិទ្យាឈានមុខគេ ដែលចូលរួមចំណែកអភិវឌ្ឍធនធានមនុស្សនៅកម្ពុជា។',
    'about.core': 'តម្លៃស្នូល',
    'about.core.desc': 'គុណភាព ភាពស្មោះត្រង់ ទំនួលខុសត្រូវ និងការអភិវឌ្ឍជាប្រចាំ គឺជាមូលដ្ឋានគ្រឹះនៃភាពជោគជ័យរបស់យើង។',
    'features.title': 'ហេតុអ្វីត្រូវជ្រើសរើសយើង?',
    'features.desc': 'គុណភាពនៃការអប់រំ និងភាពជោគជ័យរបស់អ្នក គឺជាអាទិភាពចម្បងរបស់យើង។',
    'promo.title': 'សេចក្តីប្រកាស',
    'promo.skip': 'រំលងសិន',
    'promo.register': 'ចុះឈ្មោះឥឡូវនេះ',
    'team.title': 'ក្រុមការងារ និងគ្រូបង្រៀន',
    'team.desc': 'ជួបជាមួយគ្រូបង្រៀនដែលមានបទពិសោធន៍ខ្ពស់',
    'testimonials.title': 'មតិយោបល់របស់សិស្ស',
    'testimonials.desc': 'ស្តាប់ពីបទពិសោធន៍ពិតៗរបស់សិស្សដែលធ្លាប់បានសិក្សានៅទីនេះ',
    'partners.title': 'ដៃគូសហការ និងការទទួលស្គាល់',
    'partners.desc': 'យើងមានការទទួលស្គាល់ និងសហការជាមួយស្ថាប័នបច្ចេកវិទ្យាធំៗ',
    'search.placeholder': 'ស្វែងរកវគ្គសិក្សា...',
    'footer.terms': 'គោលការណ៍ប្រើប្រាស់',
    'footer.privacy': 'គោលការណ៍ឯកជនភាព',
    'stats.students': 'សិស្សបញ្ចប់ការសិក្សា',
    'stats.experience': 'ឆ្នាំនៃបទពិសោធន៍',
    'stats.courses': 'វគ្គសិក្សា',
    'video.title': 'ទិដ្ឋភាពសាលា និងការសិក្សា',
    'video.desc': 'ស្វែងយល់បន្ថែមអំពីបរិយាកាស និងការអនុវត្តផ្ទាល់នៅក្នុងថ្នាក់រៀនរបស់យើង',
    'blog.title': 'ចែករំលែកចំណេះដឹង',
    'blog.desc': 'គន្លឹះកុំព្យូទ័រ និងព័ត៌មានបច្ចេកវិទ្យាថ្មីៗដែលអ្នកគួរដឹង',
    'careers.title': 'ឱកាសការងារ',
    'careers.desc': 'យើងមានដៃគូសហការជាច្រើន ដើម្បីជួយផ្តល់ឱកាសការងារដល់សិស្សបន្ទាប់ពីបញ្ចប់ការសិក្សា',
    'alumni.title': 'សិស្សឆ្នើមរបស់យើង',
    'alumni.desc': 'មោទនភាពចំពោះសិស្សដែលទទួលបានជោគជ័យក្នុងការងារ',



  },
  en: {
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.courses': 'Courses',
    'nav.gallery': 'Gallery',
    'nav.contact': 'Contact',
    'nav.login': 'Student Login',
    'nav.register': 'Register Now',
    'hero.badge': 'Leading IT Training Institution',
    'hero.title.1': 'Develop your digital skills with',
    'hero.title.2': 'PLC Computer',
    'hero.desc': 'We provide practical training programs that help you gain real knowledge and be ready for the job market.',
    'hero.btn.courses': 'Explore Courses',
    'hero.btn.contact': 'Contact Us',
    'courses.title': 'Main Courses',
    'courses.desc': 'Find the right course for you. Classrooms are equipped with modern computers and 100% practical training.',
    'courses.duration': 'Duration',
    'courses.details': 'Details',
    'faq.title': 'Frequently Asked Questions',
    'faq.q1': 'How long is a course?',
    'faq.a1': 'Course duration depends on each course, generally ranging from 3 to 4 months.',
    'faq.q2': 'Is there any discount for students?',
    'faq.a2': 'We have special discounts for students and group registrations.',
    'faq.q3': 'Do you provide a certificate upon completion?',
    'faq.a3': 'Yes, we provide a recognized certificate after successfully completing the course.',
    'faq.q4': 'How can I register?',
    'faq.a4': 'You can register via the online form, phone, or visit the center directly.',
    'gallery.title': 'Student Activities',
    'gallery.desc': 'Pictures of studying and practical activities',
    'gallery.alt': 'Activity',
    'contact.title': 'Contact & Register',
    'contact.desc': 'Visit our center directly or contact us via the information below',
    'contact.address': 'Address',
    'contact.address.text': 'Kbal Spean 2 Village, Sangkat O\'Chrov, Poipet City, Banteay Meanchey Province',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.form.title': 'Registration Form',
    'contact.form.name': 'Full Name',
    'contact.form.name.ph': 'Enter your name',
    'contact.form.tel': 'Phone Number',
    'contact.form.tel.ph': 'Enter phone number',
    'contact.form.course': 'Select Course',
    'contact.form.msg': 'Additional Message (optional)',
    'contact.form.msg.ph': 'Write a message...',
    'contact.form.submit': 'Submit Registration',
    'contact.form.success': 'Registered successfully! We will contact you soon.',
    'footer.desc': 'The leading computer training center providing real knowledge and quality education.',
    'footer.links': 'Quick Links',
    'footer.all_courses': 'All Courses',
    'footer.hours': 'Working Hours',
    'footer.days': 'Mon - Fri',
    'footer.time': '8:00 AM - 8:00 PM',
    'footer.copyright': 'Copyright PLC Computer.',
    'footer.location': 'Location: Poipet City',
    'footer.phone': 'Phone',
    'login.student': 'Student Portal',
    'login.admin': 'Admin Portal',
    'login.student.desc': 'Please enter your student ID and password',
    'login.admin.desc': 'Please enter your username and password',
    'login.student.btn': 'Enter Portal',
    'login.admin.btn': 'Secure Login',
    'login.user': 'Username',
    'login.student_id': 'Student ID',
    'login.pass': 'Password',
    'about.title': 'About Us',
    'about.desc': 'Discover our goals and core values',
    'about.mission': 'Mission',
    'about.mission.desc': 'Provide high-quality computer education focused on practical application to meet current job market demands.',
    'about.vision': 'Vision',
    'about.vision.desc': 'Become a leading technology training center contributing to human resource development in Cambodia.',
    'about.core': 'Core Values',
    'about.core.desc': 'Quality, integrity, responsibility, and continuous development are the foundation of our success.',
    'features.title': 'Why Choose Us?',
    'features.desc': 'Quality of education and your success are our top priorities.',
    'promo.title': 'Announcement',
    'promo.skip': 'Skip for now',
    'promo.register': 'Register Now',
    'team.title': 'Our Team & Instructors',
    'team.desc': 'Meet our highly experienced instructors',
    'testimonials.title': 'Student Testimonials',
    'testimonials.desc': 'Hear from real experiences of our former students',
    'partners.title': 'Partners & Certifications',
    'partners.desc': 'We are recognized by and partner with major tech institutions',
    'search.placeholder': 'Search courses...',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'stats.students': 'Graduated Students',
    'stats.experience': 'Years of Experience',
    'stats.courses': 'Professional Courses',
    'video.title': 'Campus & Study Environment',
    'video.desc': 'Learn more about our training center and hands-on practice in classrooms',
    'blog.title': 'IT Tips & Knowledge',
    'blog.desc': 'Computer tips and latest tech news you should know',
    'careers.title': 'Job Placements',
    'careers.desc': 'We partner with many companies to provide job opportunities for our graduates',
    'alumni.title': 'Outstanding Alumni',
    'alumni.desc': 'Proud of our successful students in their careers',



  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>('km');

  const t = (key: string) => {
    return translations[lang][key as keyof typeof translations['km']] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
